import axios from "axios";

function extractJson(text) {
  const rawText = String(text ?? "").trim();
  if (!rawText) {
    return null;
  }

  const fencedMatch = rawText.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fencedMatch ? fencedMatch[1] : rawText;

  const firstBrace = candidate.indexOf("{");
  const lastBrace = candidate.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    return null;
  }

  const jsonSlice = candidate.slice(firstBrace, lastBrace + 1);

  try {
    return JSON.parse(jsonSlice);
  } catch {
    return null;
  }
}

function normalizeTextField(value) {
  if (value === undefined || value === null) {
    return null;
  }

  const trimmed = String(value).trim();
  return trimmed ? trimmed : null;
}

function normalizeBoolean(value) {
  if (typeof value === "boolean") {
    return value;
  }

  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["true", "yes", "1"].includes(normalized)) {
      return true;
    }
    if (["false", "no", "0"].includes(normalized)) {
      return false;
    }
  }

  return null;
}

function normalizeStringArray(value) {
  if (Array.isArray(value)) {
    return value
      .map((item) => normalizeTextField(item))
      .filter(Boolean);
  }

  if (typeof value === "string") {
    return value
      .split(/[,;\n]/)
      .map((item) => normalizeTextField(item))
      .filter(Boolean);
  }

  return [];
}

function toAiMedicineRecord(query, parsed) {
  return {
    id: `ai:${query.toLowerCase().trim()}`,
    source: "ai",
    is_ai_generated: true,
    name: normalizeTextField(parsed?.name) ?? query,
    salt: normalizeTextField(parsed?.salt),
    chemical_class: normalizeTextField(parsed?.chemical_class),
    habit_forming: normalizeBoolean(parsed?.habit_forming),
    therapeutic_class: normalizeTextField(parsed?.therapeutic_class),
    action_class: normalizeTextField(parsed?.action_class),
    working: normalizeTextField(parsed?.working),
    safetyadvice: normalizeTextField(parsed?.safetyadvice),
    price: null,
    usage: normalizeTextField(parsed?.usage),
    image: null,
    link: null,
    info: normalizeTextField(parsed?.info),
    benefits: normalizeTextField(parsed?.benefits),
    sideeffects: normalizeTextField(parsed?.sideeffects),
    category: normalizeTextField(parsed?.category) ?? "AI suggested",
    created_at: null,
    updated_at: null,
    is_deleted: false,
    salts: normalizeStringArray(parsed?.salts ?? parsed?.salt),
    substitutes: normalizeStringArray(parsed?.substitutes),
    substitute_details: [],
    side_effects: normalizeStringArray(parsed?.side_effects ?? parsed?.sideeffects),
    uses: normalizeStringArray(parsed?.uses ?? parsed?.usage),
    ai_disclaimer:
      "This medicine profile was generated by AI because it was not found in the local dataset. Verify with a doctor or pharmacist before using it.",
  };
}

export async function lookupMedicineWithAi(query) {
  const trimmedQuery = String(query ?? "").trim();
  if (!trimmedQuery) {
    return null;
  }

  const apiKey = process.env.API_KEY;
  const baseUrl = process.env.BASE_URL;

  if (!apiKey || !baseUrl) {
    return null;
  }

  const response = await axios.post(
    `${baseUrl}/chat/completions`,
    {
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            "You are a medicine lookup assistant. Return strict JSON only. If the requested medicine seems real, provide a compact medicine profile. If uncertain, still provide the best-effort profile and keep uncertain fields null. JSON keys: name, salt, chemical_class, therapeutic_class, action_class, habit_forming, usage, working, safetyadvice, info, benefits, sideeffects, category, uses, side_effects, substitutes, salts.",
        },
        {
          role: "user",
          content: `Medicine name: ${trimmedQuery}`,
        },
      ],
      temperature: 0.2,
      max_tokens: 700,
      response_format: { type: "json_object" },
    },
    {
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      timeout: 12000,
    },
  );

  const text = response?.data?.choices?.[0]?.message?.content ?? "";
  const parsed = extractJson(text);

  if (!parsed) {
    return null;
  }

  return toAiMedicineRecord(trimmedQuery, parsed);
}
