 const sampleMedicines = [
  {
    "name": "AB Phylline Tablet",
    "salt": "Acebrophylline",
    "price": 150,
    "info": "Used for asthma and COPD.",
    "benefits": "Relaxes airway muscles and reduces inflammation.",
    "sideeffects": "Nausea, vomiting, dizziness.",
    "usage": "Take with food or as directed by a doctor.",
    "working": "Inhibits phosphodiesterase to reduce airway resistance.",
    "safetyadvice": "Avoid alcohol and use cautiously in heart patients.",
    "image": ""
  },
  {
    "name": "AB Phylline SR Capsule",
    "salt": "Acebrophylline",
    "price": 170,
    "info": "Used for chronic asthma symptoms.",
    "benefits": "Improves breathing and reduces lung inflammation.",
    "sideeffects": "Headache, upset stomach.",
    "usage": "Take once daily with food.",
    "working": "Acts as a bronchodilator and mucoregulator.",
    "safetyadvice": "Consult doctor if pregnant or breastfeeding.",
    "image": ""
  },
  {
    "name": "Augmentin 625 Duo Tablet",
    "salt": "Amoxycillin + Clavulanic Acid",
    "price": 250,
    "info": "Treats bacterial infections in lungs, urinary tract, and skin.",
    "benefits": "Effective against antibiotic-resistant bacteria.",
    "sideeffects": "Diarrhea, skin rash, stomach pain.",
    "usage": "Take with food to avoid stomach upset.",
    "working": "Prevents bacterial growth by inhibiting cell wall synthesis.",
    "safetyadvice": "Not for viral infections; avoid alcohol.",
    "image": ""
  },
  {
    "name": "Amoxyclav 625 Tablet",
    "salt": "Amoxycillin + Clavulanic Acid",
    "price": 240,
    "info": "Broad-spectrum antibiotic for bacterial infections.",
    "benefits": "Works against resistant bacteria.",
    "sideeffects": "Nausea, diarrhea, headache.",
    "usage": "Take twice daily with meals.",
    "working": "Stops bacteria from forming cell walls.",
    "safetyadvice": "Avoid if allergic to penicillin.",
    "image": ""
  },
  {
    "name": "Montair LC Tablet",
    "salt": "Montelukast + Levocetirizine",
    "price": 180,
    "info": "Used for allergies and asthma symptoms.",
    "benefits": "Relieves sneezing, runny nose, and wheezing.",
    "sideeffects": "Drowsiness, dry mouth.",
    "usage": "Take before bedtime.",
    "working": "Blocks histamine and leukotrienes.",
    "safetyadvice": "Do not drive after taking.",
    "image": ""
  },
  {
    "name": "Montek LC Tablet",
    "salt": "Montelukast + Levocetirizine",
    "price": 175,
    "info": "Antiallergic tablet for seasonal allergies.",
    "benefits": "Reduces inflammation and airway constriction.",
    "sideeffects": "Dizziness, headache.",
    "usage": "Take daily in the evening.",
    "working": "Acts as leukotriene receptor antagonist.",
    "safetyadvice": "Avoid alcohol and heavy machinery.",
    "image": ""
  },
  {
    "name": "Pantocid DSR Capsule",
    "salt": "Pantoprazole + Domperidone",
    "price": 190,
    "info": "Used for acid reflux and digestive issues.",
    "benefits": "Reduces stomach acid and nausea.",
    "sideeffects": "Headache, constipation.",
    "usage": "Take before meals.",
    "working": "Blocks proton pump and dopamine receptors.",
    "safetyadvice": "Avoid spicy food.",
    "image": ""
  },
  {
    "name": "Pantop D Tablet",
    "salt": "Pantoprazole + Domperidone",
    "price": 185,
    "info": "Used for gastritis and acid reflux.",
    "benefits": "Protects stomach lining.",
    "sideeffects": "Diarrhea, stomach pain.",
    "usage": "Take once daily on an empty stomach.",
    "working": "Decreases acid production and controls nausea.",
    "safetyadvice": "Consult doctor if pregnant.",
    "image": ""
  },
  {
    "name": "Cefixime 200 Tablet",
    "salt": "Cefixime",
    "price": 300,
    "info": "Used for bacterial infections.",
    "benefits": "Effective against urinary tract and respiratory infections.",
    "sideeffects": "Stomach pain, indigestion.",
    "usage": "Take with water.",
    "working": "Inhibits bacterial cell wall synthesis.",
    "safetyadvice": "Do not skip doses.",
    "image": ""
  }
,
    {
        name: "Warfarin Sodium",
        price: 100,
        info: "Warfarin is an anticoagulant used to prevent blood clots.",
        category: "Anticoagulant",
        salt: "Warfarin Sodium",
        benefits: "Prevents blood clots, reduces risk of stroke.",
        sideeffects: "Bleeding, nausea, diarrhea.",
        usage: "As directed by a healthcare provider.",
        working: "Inhibits vitamin K epoxide reductase, reducing clotting factors.",
        safetyadvice: "Avoid alcohol, monitor INR levels regularly.",
        image: "https://example.com/warfarin.jpg"
    },
    {
        name: "Paracetamol",
        price: 50,
        info: "Used for pain relief and fever reduction.",
        category: "Painkiller",
        salt: "Paracetamol",
        benefits: "Reduces fever and relieves mild to moderate pain.",
        sideeffects: "Nausea, liver damage (if overdosed).",
        usage: "Take one tablet every 6 hours with water.",
        working: "Blocks pain signals and reduces fever.",
        safetyadvice: "Do not exceed 4 grams per day.",
        image: "https://example.com/paracetamol.jpg"
    },
    {
        name: "Ibuprofen",
        price: 80,
        info: "Non-steroidal anti-inflammatory drug (NSAID) for pain relief.",
        category: "NSAID",
        salt: "Ibuprofen",
        benefits: "Reduces inflammation, pain, and fever.",
        sideeffects: "Stomach pain, nausea, dizziness.",
        usage: "Take with food to avoid stomach irritation.",
        working: "Inhibits COX enzymes to reduce inflammation.",
        safetyadvice: "Avoid excessive use to prevent kidney damage.",
        image: "https://example.com/ibuprofen.jpg"
    },
    {
        name: "Amoxicillin",
        price: 120,
        info: "Broad-spectrum antibiotic used to treat bacterial infections.",
        category: "Antibiotic",
        salt: "Amoxicillin",
        benefits: "Treats respiratory, urinary, and skin infections.",
        sideeffects: "Diarrhea, nausea, rash.",
        usage: "Take as prescribed by a doctor.",
        working: "Inhibits bacterial cell wall synthesis.",
        safetyadvice: "Complete full course to prevent resistance.",
        image: "https://example.com/amoxicillin.jpg"
    },
    {
        name: "Metformin",
        price: 90,
        info: "Used to manage type 2 diabetes by lowering blood sugar levels.",
        category: "Diabetes Medication",
        salt: "Metformin Hydrochloride",
        benefits: "Improves insulin sensitivity, lowers glucose production.",
        sideeffects: "Nausea, diarrhea, stomach pain.",
        usage: "Take with meals to reduce stomach upset.",
        working: "Reduces liver glucose production and increases insulin sensitivity.",
        safetyadvice: "Monitor blood sugar levels regularly.",
        image: "https://example.com/metformin.jpg"
    },
    {
        name: "Aspirin",
        price: 60,
        info: "Used for pain relief, fever reduction, and heart health.",
        category: "Painkiller & Antiplatelet",
        salt: "Acetylsalicylic Acid",
        benefits: "Reduces pain, inflammation, and prevents blood clots.",
        sideeffects: "Stomach irritation, bleeding risk.",
        usage: "Take with food to avoid stomach upset.",
        working: "Inhibits COX enzymes and platelet aggregation.",
        safetyadvice: "Avoid excessive use to prevent bleeding complications.",
        image: "https://example.com/aspirin.jpg"
    },
    {
        name: "Ciprofloxacin",
        price: 150,
        info: "Broad-spectrum antibiotic used for bacterial infections.",
        category: "Antibiotic",
        salt: "Ciprofloxacin Hydrochloride",
        benefits: "Treats respiratory, urinary, and gastrointestinal infections.",
        sideeffects: "Nausea, dizziness, tendon pain.",
        usage: "Take with water, avoid dairy products.",
        working: "Inhibits bacterial DNA replication.",
        safetyadvice: "Avoid excessive sun exposure while taking.",
        image: "https://example.com/ciprofloxacin.jpg"
    },
    {
        name: "Omeprazole",
        price: 110,
        info: "Used to treat acid reflux and stomach ulcers.",
        category: "Proton Pump Inhibitor",
        salt: "Omeprazole",
        benefits: "Reduces stomach acid production.",
        sideeffects: "Headache, nausea, diarrhea.",
        usage: "Take before meals for best effect.",
        working: "Inhibits proton pumps in stomach lining.",
        safetyadvice: "Avoid long-term use without medical supervision.",
        image: "https://example.com/omeprazole.jpg"
    },
    {
        name: "Losartan",
        price: 130,
        info: "Used to treat high blood pressure and heart conditions.",
        category: "Antihypertensive",
        salt: "Losartan Potassium",
        benefits: "Lowers blood pressure, protects kidney function.",
        sideeffects: "Dizziness, fatigue, cough.",
        usage: "Take once daily as prescribed.",
        working: "Blocks angiotensin receptors to relax blood vessels.",
        safetyadvice: "Monitor blood pressure regularly.",
        image: "https://example.com/losartan.jpg"
    },
    {
        name: "Atorvastatin",
        price: 140,
        info: "Used to lower cholesterol and prevent heart disease.",
        category: "Statin",
        salt: "Atorvastatin Calcium",
        benefits: "Reduces LDL cholesterol, improves heart health.",
        sideeffects: "Muscle pain, liver enzyme changes.",
        usage: "Take in the evening for best effect.",
        working: "Inhibits HMG-CoA reductase enzyme.",
        safetyadvice: "Monitor liver function tests regularly.",
        image: "https://example.com/atorvastatin.jpg"
    }
];


module.exports = {data:sampleMedicines};
